#!/usr/bin/python3

def raise_exception_msg(message=""):
    """Raises a name exception with a message

    args:
            message: Message in the name exception

    """
    raise NameError(message)
